[package]
name = "neonorigami"
version = "0.0.0"
authors = ["richard"]
edition = "2018"
description = "A library for virtual worlds"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
